# Generated by Django 6.0.5 on 2026-05-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='sent at'),
        ),
    ]
