# Generated by Django 6.0.5 on 2026-05-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0002_alter_message_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden_for_recipient',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_for_sender',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
